config/routes.rb
Rails.application.routes.draw do

  resources :config_columns
  resources :config_view_columns
  scope "(:locale)" do

    resources :ability_requirements
    resources :ability_groupings
    resources :config_form_columns
    resources :config_form_footers
    resources :config_views
    resources :evaluation_details
    resources :evaluation_headers do
      member do
        get :entry
        get :edit_evaluator
      end
    end
    resources :evaluation_settings
    resources :evaluation_objectives do
      member do
        get :delete
      end
    end

    resources :evaluation_events do
      member do
        get :delete
      end
    end
    resources :members do
      member do
        get :profile_tabs
        get :profile_details
        get :profile
      end
    end
    resources :member_communications do
      collection do
        get :cancel_edit
      end
    end
    resources :member_names do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_systems do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_tables
    resources :member_role_details do
      member do
        get :block_edit
      end
    end
    resources :member_roles
    resources :table_settings
    resources :user_images
    resources :user_passwords
    resources :users do
      collection do
        get :activate
        get :account_new
        post :account_create
        get :account_finish
        get :password_reset_check
        get :password_reset_error
        get :password_reset_finish
      end
      member do
        get :password_reset
        patch :password_reset_update
        get :delete
      end
    end

    get  'login' => 'login#index'
    post 'login/auth' => 'login#auth'

    get  'logout' => 'login#logout'

    get  'registers' => 'registers#index'
    post 'registers/auth' => 'registers#auth'
    post 'registers/email_check' => 'registers#email_check'
    get  'registers/password_reset' => 'registers#password_reset'

    get  'configurations' => 'configurations#index'

    get  'homes/user' => 'homes#user'
    get  'evaluations/index' => 'evaluations#index'
    get  'members/profile/:id' => 'members#profile'

  end

end

app/models/config_form_column.rb
class ConfigFormColumn < ActiveRecord::Base
  belongs_to :config_view
  belongs_to :config_column

  #入力フォーム項目
  scope :get_visible_column, ->(congig_view_id) { where(config_view_id: congig_view_id).where(visible: true).order("view_order") }

end

app/controllers/config_form_columns_controller.rb
class ConfigFormColumnsController < ApplicationController
  before_action :set_config_form_column, only: [:show, :edit, :update, :destroy]

  # GET /config_form_columns
  # GET /config_form_columns.json
  def index
    @config_form_columns = ConfigFormColumn.all
  end

  # GET /config_form_columns/1
  # GET /config_form_columns/1.json
  def show
  end

  # GET /config_form_columns/new
  def new
    @config_form_column = ConfigFormColumn.new
  end

  # GET /config_form_columns/1/edit
  def edit
  end

  # POST /config_form_columns
  # POST /config_form_columns.json
  def create
    @config_form_column = ConfigFormColumn.new(config_form_column_params)

    respond_to do |format|
      if @config_form_column.save
        format.html { redirect_to @config_form_column, notice: 'Config form column was successfully created.' }
        format.json { render :show, status: :created, location: @config_form_column }
      else
        format.html { render :new }
        format.json { render json: @config_form_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /config_form_columns/1
  # PATCH/PUT /config_form_columns/1.json
  def update
    respond_to do |format|
      if @config_form_column.update(config_form_column_params)
        format.html { redirect_to @config_form_column, notice: 'Config form column was successfully updated.' }
        format.json { render :show, status: :ok, location: @config_form_column }
      else
        format.html { render :edit }
        format.json { render json: @config_form_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /config_form_columns/1
  # DELETE /config_form_columns/1.json
  def destroy
    @config_form_column.destroy
    respond_to do |format|
      format.html { redirect_to config_form_columns_url, notice: 'Config form column was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config_form_column
      @config_form_column = ConfigFormColumn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_form_column_params
      params.require(:config_form_column).permit(:config_view_id, :column_name, :attribute_type, :standard, :visible, :order, :custom_name_ja, :custom_name_en, :custom_name_zh, :description_ja, :description_en, :description_zh, :required, :default, :sys_lower, :sys_high, :custom_lower, :custom_high, :grid_class_label, :grid_class_value, :data_source)
    end
end

app/views/config_form_columns/_form.html.slim
= form_for @config_form_column do |f|
  - if @config_form_column.errors.any?
    #error_explanation
      h2 = "#{pluralize(@config_form_column.errors.count, "error")} prohibited this config_form_column from being saved:"
      ul
        - @config_form_column.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :config_view_id
    = f.number_field :config_view_id
  .field
    = f.label :column_name
    = f.text_field :column_name
  .field
    = f.label :attribute_type
    = f.text_field :attribute_type
  .field
    = f.label :standard
    = f.check_box :standard
  .field
    = f.label :visible
    = f.check_box :visible
  .field
    = f.label :order
    = f.number_field :order
  .field
    = f.label :custom_name_ja
    = f.text_field :custom_name_ja
  .field
    = f.label :custom_name_en
    = f.text_field :custom_name_en
  .field
    = f.label :custom_name_zh
    = f.text_field :custom_name_zh
  .field
    = f.label :description_ja
    = f.text_field :description_ja
  .field
    = f.label :description_en
    = f.text_field :description_en
  .field
    = f.label :description_zh
    = f.text_field :description_zh
  .field
    = f.label :required
    = f.check_box :required
  .field
    = f.label :default
    = f.number_field :default
  .field
    = f.label :sys_lower
    = f.number_field :sys_lower
  .field
    = f.label :sys_high
    = f.number_field :sys_high
  .field
    = f.label :custom_lower
    = f.number_field :custom_lower
  .field
    = f.label :custom_high
    = f.number_field :custom_high
  .field
    = f.label :grid_class_label
    = f.text_field :grid_class_label
  .field
    = f.label :grid_class_value
    = f.text_field :grid_class_value
  .field
    = f.label :data_source
    = f.text_field :data_source
  .actions = f.submit

app/views/config_form_columns/edit.html.slim
h1 Editing config_form_column

== render 'form'

= link_to 'Show', @config_form_column
'|
= link_to 'Back', config_form_columns_path

app/views/config_form_columns/index.html.slim
h1 Listing config_form_columns

table
  thead
    tr
      th Config view
      th Column name
      th Attribute type
      th Standard
      th Visible
      th Order
      th Custom name ja
      th Custom name en
      th Custom name zh
      th Description ja
      th Description en
      th Description zh
      th Required
      th Default
      th Sys lower
      th Sys high
      th Custom lower
      th Custom high
      th Grid class label
      th Grid class value
      th Data source
      th
      th
      th

  tbody
    - @config_form_columns.each do |config_form_column|
      tr
        td = config_form_column.config_view_id
        td = config_form_column.column_name
        td = config_form_column.attribute_type
        td = config_form_column.standard
        td = config_form_column.visible
        td = config_form_column.order
        td = config_form_column.custom_name_ja
        td = config_form_column.custom_name_en
        td = config_form_column.custom_name_zh
        td = config_form_column.description_ja
        td = config_form_column.description_en
        td = config_form_column.description_zh
        td = config_form_column.required
        td = config_form_column.default
        td = config_form_column.sys_lower
        td = config_form_column.sys_high
        td = config_form_column.custom_lower
        td = config_form_column.custom_high
        td = config_form_column.grid_class_label
        td = config_form_column.grid_class_value
        td = config_form_column.data_source
        td = link_to 'Show', config_form_column
        td = link_to 'Edit', edit_config_form_column_path(config_form_column)
        td = link_to 'Destroy', config_form_column, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Config form column', new_config_form_column_path

app/views/config_form_columns/new.html.slim
h1 New config_form_column

== render 'form'

= link_to 'Back', config_form_columns_path

app/views/config_form_columns/show.html.slim
p#notice = notice

p
  strong Config view:
  = @config_form_column.config_view_id
p
  strong Column name:
  = @config_form_column.column_name
p
  strong Attribute type:
  = @config_form_column.attribute_type
p
  strong Standard:
  = @config_form_column.standard
p
  strong Visible:
  = @config_form_column.visible
p
  strong Order:
  = @config_form_column.order
p
  strong Custom name ja:
  = @config_form_column.custom_name_ja
p
  strong Custom name en:
  = @config_form_column.custom_name_en
p
  strong Custom name zh:
  = @config_form_column.custom_name_zh
p
  strong Description ja:
  = @config_form_column.description_ja
p
  strong Description en:
  = @config_form_column.description_en
p
  strong Description zh:
  = @config_form_column.description_zh
p
  strong Required:
  = @config_form_column.required
p
  strong Default:
  = @config_form_column.default
p
  strong Sys lower:
  = @config_form_column.sys_lower
p
  strong Sys high:
  = @config_form_column.sys_high
p
  strong Custom lower:
  = @config_form_column.custom_lower
p
  strong Custom high:
  = @config_form_column.custom_high
p
  strong Grid class label:
  = @config_form_column.grid_class_label
p
  strong Grid class value:
  = @config_form_column.grid_class_value
p
  strong Data source:
  = @config_form_column.data_source

= link_to 'Edit', edit_config_form_column_path(@config_form_column)
'|
= link_to 'Back', config_form_columns_path