config/routes.rb
Rails.application.routes.draw do

  resources :config_columns
  resources :config_view_columns
  scope "(:locale)" do

    resources :ability_requirements
    resources :ability_groupings
    resources :config_form_columns
    resources :config_form_footers
    resources :config_views
    resources :evaluation_details
    resources :evaluation_headers do
      member do
        get :entry
        get :edit_evaluator
      end
    end
    resources :evaluation_settings
    resources :evaluation_objectives do
      member do
        get :delete
      end
    end

    resources :evaluation_events do
      member do
        get :delete
      end
    end
    resources :members do
      member do
        get :profile_tabs
        get :profile_details
        get :profile
      end
    end
    resources :member_communications do
      collection do
        get :cancel_edit
      end
    end
    resources :member_names do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_systems do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_tables
    resources :member_role_details do
      member do
        get :block_edit
      end
    end
    resources :member_roles
    resources :table_settings
    resources :user_images
    resources :user_passwords
    resources :users do
      collection do
        get :activate
        get :account_new
        post :account_create
        get :account_finish
        get :password_reset_check
        get :password_reset_error
        get :password_reset_finish
      end
      member do
        get :password_reset
        patch :password_reset_update
        get :delete
      end
    end

    get  'login' => 'login#index'
    post 'login/auth' => 'login#auth'

    get  'logout' => 'login#logout'

    get  'registers' => 'registers#index'
    post 'registers/auth' => 'registers#auth'
    post 'registers/email_check' => 'registers#email_check'
    get  'registers/password_reset' => 'registers#password_reset'

    get  'configurations' => 'configurations#index'

    get  'homes/user' => 'homes#user'
    get  'evaluations/index' => 'evaluations#index'
    get  'members/profile/:id' => 'members#profile'

  end

end

app/models/member_name.rb
class MemberName < ActiveRecord::Base

  belongs_to :user

  default_scope { where("member_names.deleted_at IS NULL") }

  #対象者の全レコード
  scope :get_mylist, ->(id) { where(user_id: id).order(started_on: :desc) }
  #対象者の現時点で有効なレコード
  scope :get_mylist_active, ->(id) { where(user_id: id).where('started_on <=?', Date.current ).where('ended_on >=?',Date.current).first }
  #対象者の特定の終了日のレコード
  scope :get_mylist_day, ->(id,day) { where(user_id: id).where(ended_on: day).first }

  #CSV出力
  def self.to_csv(member_names,options = {})
    csv_data = CSV.generate(force_quotes: true) do |csv|
      csv << csv_column_names
      member_names.each do |member_name|
        csv << member_name.csv_column_values
      end
    end
    csv_data.encode(Encoding::SJIS)
  end

  def self.csv_column_names
    [
        MemberName.human_attribute_name("started_on"),
        MemberName.human_attribute_name("ended_on"),
        User.human_attribute_name("code"),
        MemberName.human_attribute_name("name"),
        MemberName.human_attribute_name("name_katakana"),
        MemberName.human_attribute_name("name_romaji"),
        MemberName.human_attribute_name("register"),
        MemberName.human_attribute_name("register_katakana"),
        MemberName.human_attribute_name("register_romaji"),
        MemberName.human_attribute_name("memo")
    ]
  end

  def csv_column_values
    [
        started_on,
        ended_on,
        user.code,
        name,
        name_katakana,
        name_romaji,
        register,
        register_katakana,
        register_romaji,
        memo
    ]
  end

end

app/controllers/member_names_controller.rb
class MemberNamesController < ApplicationController
  include Member
  before_action :set_member_menu, only: [:index]
  before_action :set_member_name, only: [:edit, :update, :destroy]

  def index

    #検索フォーム
    if params[:q].blank?
      #初回ロード時
      @q = MemberName.order(updated_at: :desc).where(updated_status: [1,2] ).ransack(params[:q])
    else
      #検索実行時
      @q = MemberName.order(updated_at: :desc).ransack(params[:q])
    end

    #結果表示
    @results = @q.result(distinct: true).page(params[:page])
    @member_table = MemberTable.where(controller: "member_names").first

  end

  def new

    @user_id = params[:user_id]
    @table_settings = TableSetting.get_input_list('member_names')

    record_old = MemberName.get_mylist_day(params[:user_id],'2099-12-31')
    @record = MemberName.new
    @table_settings.each do |table_setting|
      @record["#{table_setting.column_name}"] = record_old["#{table_setting.column_name}"]
    end
    @record.started_on = Date.parse(@record.started_on.to_s) + 1

  end

  def create
    ##新規登録
    @member_name = MemberName.new(member_name_params)
    @member_name.updated_status = 1
    @member_name.updated_user = session[:user_id]

    ##レコード作成
    #1.更新前の最新履歴を取得
    update_record = MemberName.get_mylist_day(params[:member_name][:user_id],'2099-12-31')

    #2.新規レコード追加
    @member_name.save

    #3.1で取得したレコードの終了日を更新
    day = Date.parse(params[:member_name][:started_on])
    update_record.ended_on = day - 1
    update_record.updated_user = session[:user_id]
    update_record.save

    ##ページ再表示
    flash[:notice] = t('message.save')
    set_member_list(params[:member_name][:user_id],"member_names")

  end

  def cancel
  end

  def cancel_edit
    @id = params[:id]
  end

  def edit

    @id = params[:id]
    @member_table = MemberTable.where(controller: "member_names").first
    record = MemberName.find(params[:id])
    @record_old = MemberName.get_mylist_day(@record.user_id,record.started_on - 1)

    @user_id = @record.user_id
    @table_settings = TableSetting.get_input_list('member_names')

  end

  def update

    ##レコード更新
    #更新前のレコードを取得し、開始日の変更有無を確認
    before_record = MemberName.find(params[:id])

    #対象レコードの更新
    @record.updated_status = 2
    @record.update(member_name_params)

    ##開始日に変更がある場合は前のレコードの終了日を合わせて更新
    unless before_record.started_on == Date.parse(params[:member_name][:started_on])
      #対象レコードを取得
      day = before_record.started_on - 1
      update_record = MemberName.get_mylist_day(params[:member_name][:user_id],day)
      #終了日を更新
      update_day = Date.parse(params[:member_name][:started_on]) - 1
      update_record.ended_on = update_day
      update_record.updated_status = 4
      update_record.updated_user = session[:user_id]
      update_record.save
    end

    ##ページ再表示
    flash[:notice] = t('message.update')
    set_member_list(params[:member_name][:user_id],"member_names")

  end

  def destroy
    ##削除処理

    #1つ前の履歴の終了日を無期限に変更
    day = Date.parse(@record.started_on.to_s) - 1
    update_record = MemberName.get_mylist_day(@record.user_id,day)
    update_record.ended_on = '2099-12-31'
    update_record.updated_status = 4
    update_record.updated_user = session[:user_id]
    update_record.save

    #対象レコードを削除
    @record.updated_status = 3
    @record.updated_user = session[:user_id]
    @record.deleted_at = Time.now
    @record.save

    ##ページ再表示
    flash[:notice]  = t('message.delete')
    set_member_list(@record.user_id,"member_names")

  end

  def csv
    set_member_list(params[:user_id],"member_names")
    respond_to do |format|
      format.csv do
        send_data MemberName.to_csv(@member_names),
                  type: 'text/csv; charset=shift_jis',
                  filename: "member_name-#{Time.now.to_date.to_s}.csv",
                  type: :csv
      end
    end
  end

  private

  def set_member_name
    @record = MemberName.find(params[:id])
  end
  def member_name_params
    params.require(:member_name).permit(:user_id, :started_on, :ended_on, :name, :name_katakana, :name_romaji, :register, :register_katakana, :register_romaji, :memo)
  end

end

app/views/member_names/_edit.html.slim
.panel.panel-success
  .panel-heading
    h3.panel-title
      = t('link.edit')
  .panel-body
    = form_for(@record, remote: true) do |f|
      = f.hidden_field :user_id
      = f.hidden_field :ended_on

      .row
        .form-horizontal.col-xs-12.col-md-8
          == render :partial => 'shared/form', :locals => {:f => f}

          .col-md-8.col-md-offset-4
            = button_tag :type => "submit", class: "btn btn-success" do
              i.fa.fa-floppy-o
              '
              = t('link.save')
            '
            = link_to cancel_edit_member_names_path(id: @record.id), class: "btn btn-danger", :remote => true do
              i.fa.fa-close
              '
              = t('link.cancel')

app/views/member_names/_list.html.slim
== render 'shared/member_navi'

.row
  .col-xs-12.col-md-6
    = link_to '#' , id: "open_all" do
      i.fa.fa-plus-square-o
      '
      u
        = t('veiw_control.open_all')
      '
    = link_to '#' , id: "close_all" do
      i.fa.fa-minus-square-o
      '
      u
        = t('veiw_control.close_all')

  .col-xs-12.col-md-3
    p.text-right
      = link_to csv_member_names_path(format: :csv , user_id: @user_id) do
        i.fa.fa-download
        '
        u
          = t('veiw_control.file_export')
      '
  .col-xs-12.col-md-3
    p.text-right
      = link_to new_member_name_path(user_id: @user_id), :remote => true do
        i.fa.fa-plus-square
        '
        u
          = t('link.new_history')

.row
#alert
#new

/リスト表示
- @member_names.each.with_index(1)  do |member_name , i |

  /現在有効なレコードを判定
  - if member_name.started_on > Date.current
    /未来
    - open = ""
    - panel_color = "panel-warning"
  - elsif member_name.started_on <= Date.current and member_name.ended_on >= Date.current
    /現在
    - open = "in"
    - panel_color = "panel-info"
  - else
    /過去
    - open = ""
    - panel_color = "panel-default"

  div id = "#{member_name.id}"
    .panel-group id="accordion" role="tablist" aria-multiselectable="true"
      .panel class= "#{panel_color}"
        .panel-heading role="tab" id="headingTwo"
          .panel-title
            .text-left.pull-left
              a.collapsed role="button" data-toggle="collapse" data-parent="#accordion" href="#record#{member_name.id}" aria-expanded="true" aria-controls="record#{member_name.id}"
                = member_name.started_on unless member_name.started_on.strftime("%Y-%m-%d") == '1900-01-01'
                '
                | ～
                '
                = member_name.ended_on unless member_name.ended_on.strftime("%Y-%m-%d") == '2099-12-31'

            p.text-right
              = link_to edit_member_name_path(member_name.id) , :remote => true do
                i.fa.fa-pencil-square-o
                '
                u
                  = t('link.edit')
              '
              /最新履歴のみ削除ボタンを表示
              - if i == 1
                = link_to member_name_path(member_name.id), method: :delete, data: {confirm: t('message.delete_alert')}, :remote => true  do
                  i.fa.fa-trash-o
                  '
                  u
                    = t('link.delete')

        .panel-collapse class ="collapse #{open}" id="record#{member_name.id}" role="tabpanel" aria-labelledby="headingTwo"
          .panel-body
            - @table_settings.each do |table_setting|
              .col-xs-12.col-md-3
                b.text-left
                  = table_setting.custom_name_ja.blank? ? MemberName.human_attribute_name(table_setting.column_name) : table_setting.custom_name_ja
              .col-xs-12.col-md-3
                .text-left
                  = member_name["#{table_setting.column_name}"].blank? ? "-" : member_name["#{table_setting.column_name}"]

  div id = "#{member_name.id}_edit"

app/views/member_names/_new.html.slim
.panel.panel-success
  .panel-heading
    h3.panel-title
      = t('link.new_history')
  .panel-body
    = form_for(@record, remote: true) do |f|

      = f.hidden_field :user_id, :value => @user_id
      = f.hidden_field :ended_on, :value => "2099-12-31"

      .row
        .form-horizontal.col-xs-12.col-md-8
          == render :partial => 'shared/form', :locals => {:f => f}

          .col-md-8.col-md-offset-4
            = button_tag :type => "submit", class: "btn btn-success" do
              i.fa.fa-floppy-o
              '
              = t('link.save')
              '
            '
            = link_to cancel_member_names_path, class: "btn btn-danger", :remote => true do
              i.fa.fa-close
              '
              = t('link.cancel')

app/views/member_names/_result.html.slim
== render :partial => 'shared/paginate' , locals: {results: @results}

- url_options = { action: :index }
- html_options = { remote: true, method: :get }

.col-xs-12.col-md-12
  table.table.table-hover
    thead
      tr
        th
        th = sort_link(@q, :code, User.human_attribute_name('code'), url_options, html_options)
        th = sort_link(@q, :name, MemberName.human_attribute_name('name'), url_options, html_options)
        th
        th = sort_link(@q, :name, MemberName.human_attribute_name('started_on'), url_options, html_options)
        th = sort_link(@q, :name, MemberName.human_attribute_name('updated_at'), url_options, html_options)
        th
          |  最終更新者
    tbody
      - @results.each do |member_name|
        tr
          td
            = image_tag(member_name.user.image.url, :size => "30x30")
          td
            = member_name.user.code
          td
            u
              = link_to ({controller: :members, action: "profile" , id: member_name.user_id , code: @member_table.code}) do
                = member_name.name
                '
                i.fa.fa-external-link
          td
          td
            = member_name.started_on
          td
            = member_name.updated_at
          td

app/views/member_names/cancel.js.erb
$("#new").html("")

app/views/member_names/cancel_edit.js.erb
$("#<%= @id %>_edit").empty();
$("#<%= @id %>").show();

app/views/member_names/create.js.erb
$("#list").html("<%= escape_javascript(render :partial => "list") %>");
$("#alert").html("<div class='alert alert-success'><a class='close' data-dismiss='alert'>×</a><%= escape_javascript(flash[:notice])%></div>");

app/views/member_names/destroy.js.erb
$("#list").html("<%= escape_javascript(render :partial => "list") %>");
$("#alert").html("<div class='alert alert-success'><a class='close' data-dismiss='alert'>×</a><%= escape_javascript(flash[:notice])%></div>");

app/views/member_names/edit.js.erb
$("#<%= @id %>").hide();
$("#<%= @id %>_edit").html("<%= escape_javascript(render 'edit') %>")

$(function($){
  $(".edit_member_name").validationEngine();
  $('.input-group.date').datepicker({
    language: 'ja',
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked"
  });
});

app/views/member_names/index.html.slim
== render 'shared/member_menu'
br
br
.row
  .col-xs-12.col-md-8

    = search_form_for @q, :remote => true do |f|
      .col-md-9.form-inline
        = f.hidden_field :started_on_lteq , value: Date.current
        = f.hidden_field :ended_on_gteq, value: Date.current
        = f.search_field :name_cont, class: "form-control"
        '
        = button_tag :type => "submit", name: 's', class: "btn btn-primary" , id: "search_btn" do
          i.fa.fa-search
          '
          = t('link.search')

  /検索結果部分
.row
  #result
    == render "result"

app/views/member_names/index.js.erb
$("#result").html("<%= escape_javascript(render :partial => 'result') %>");

app/views/member_names/new.js.erb
$("#new").html("")
$("#new").html("<%= escape_javascript(render 'new') %>")

$(function($){
  $("#new_member_name").validationEngine();
  $('.input-group.date').datepicker({
    language: 'ja',
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked"
  });
});

app/views/member_names/update.js.erb
$("#list").html("<%= escape_javascript(render :partial => "list") %>");
$("#alert").html("<div class='alert alert-success'><a class='close' data-dismiss='alert'>×</a><%= escape_javascript(flash[:notice])%></div>");