config/routes.rb
Rails.application.routes.draw do

  resources :config_columns
  resources :config_view_columns
  scope "(:locale)" do

    resources :ability_requirements
    resources :ability_groupings
    resources :config_form_columns
    resources :config_form_footers
    resources :config_views
    resources :evaluation_details
    resources :evaluation_headers do
      member do
        get :entry
        get :edit_evaluator
      end
    end
    resources :evaluation_settings
    resources :evaluation_objectives do
      member do
        get :delete
      end
    end

    resources :evaluation_events do
      member do
        get :delete
      end
    end
    resources :members do
      member do
        get :profile_tabs
        get :profile_details
        get :profile
      end
    end
    resources :member_communications do
      collection do
        get :cancel_edit
      end
    end
    resources :member_names do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_systems do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_tables
    resources :member_role_details do
      member do
        get :block_edit
      end
    end
    resources :member_roles
    resources :table_settings
    resources :user_images
    resources :user_passwords
    resources :users do
      collection do
        get :activate
        get :account_new
        post :account_create
        get :account_finish
        get :password_reset_check
        get :password_reset_error
        get :password_reset_finish
      end
      member do
        get :password_reset
        patch :password_reset_update
        get :delete
      end
    end

    get  'login' => 'login#index'
    post 'login/auth' => 'login#auth'

    get  'logout' => 'login#logout'

    get  'registers' => 'registers#index'
    post 'registers/auth' => 'registers#auth'
    post 'registers/email_check' => 'registers#email_check'
    get  'registers/password_reset' => 'registers#password_reset'

    get  'configurations' => 'configurations#index'

    get  'homes/user' => 'homes#user'
    get  'evaluations/index' => 'evaluations#index'
    get  'members/profile/:id' => 'members#profile'

  end

end

app/models/member_system.rb
class MemberSystem < ActiveRecord::Base
  extend Enumerize
  enumerize :enable, in: {:enable => 'true' , :anenable => 'false'}

  belongs_to :user
  belongs_to :member_role

  default_scope { where("member_systems.deleted_at IS NULL") }

  #対象者の全レコード
  scope :get_mylist, ->(user_id) { where(user_id: user_id).order(started_on: :desc) }
  #対象者の現時点で有効なレコード
  scope :get_mylist_active, ->(user_id) { where(user_id: user_id).where('started_on <=?', Date.current ).where('ended_on >=?',Date.current).first }
  #対象者の特定の終了日のレコード
  scope :get_mylist_day, ->(user_id,day) { where(user_id: user_id).where(ended_on: day).first }

end

app/controllers/member_systems_controller.rb
class MemberSystemsController < ApplicationController
  include Member,Common
  before_action :set_member_menu, only: [:index]
  before_action :set_view, only: [:index]

  before_action :set_member_system, only: [:show, :edit, :update, :destroy]

  def index

    #検索フォーム
    if params[:q].blank?
      #初回ロード時
      @q = MemberSystem.order(updated_at: :desc).where(updated_status: [1,2] ).ransack(params[:q])
    else
      #検索実行時
      @q = MemberSystem.order(updated_at: :desc).ransack(params[:q])
    end

    #結果表示
    @results = @q.result(distinct: true).page(params[:page])
    @member_table = MemberTable.where(controller: "member_systems").first

  end

  def new

    @forms = ConfigView.where(id: 3).first
    @form_columns = ConfigFormColumn.get_visible_column(3)
    @form_footers = ConfigFormFooter.where(form_id: 3)

    @record = MemberSystem.new

    #最新レコードを取得し、フォーム上の初期値をセット
    record_old = MemberSystem.get_mylist_day(params[:user_id],'2099-12-31')
    table_settings_value = TableSetting.get_list_value('member_system')
    table_settings_value.each do |table_setting|
      @record["#{table_setting.column_name}"] = record_old["#{table_setting.column_name}"]
    end
    @record.started_on = Date.parse(@record.started_on.to_s) + 1

  end

  def create
    ##新規登録
    @member_system = MemberSystem.new(member_system_params)
    @member_system.updated_status = 1
    @member_system.updated_user = session[:user_id]

    ##レコード作成
    #1.更新前の最新履歴を取得
    update_record = MemberSystem.get_mylist_day(params[:member_system][:user_id],'2099-12-31')

    #2.新規レコード追加
    @member_system.save

    #3.1で取得したレコードの終了日を更新
    day = Date.parse(params[:member_system][:started_on])
    update_record.ended_on = day - 1
    update_record.updated_user = session[:user_id]
    update_record.save

    ##ページ再表示
    flash[:notice] = t('message.save')
    set_member_list(params[:member_system][:user_id],"MemberSystem")

  end

  def cancel
  end

  def cancel_edit
    @id = params[:id]
  end

  def edit

    @forms = ConfigView.where(id: 4).first
    @form_columns = ConfigFormColumn.get_visible_column(4)
    @form_footers = ConfigFormFooter.where(config_view_id: 4)

    @id = params[:id]
    @member_table = MemberTable.where(controller: "member_systems").first
    record = MemberSystem.find(params[:id])
    @record_old = MemberSystem.get_mylist_day(@record.user_id,record.started_on - 1)

    @user_id = @record.user_id
    @table_settings = TableSetting.get_list_input('member_system')

  end

  def show
    @id = params[:id]
  end

  def update

    ##レコード更新
    #更新前のレコードを取得し、開始日の変更有無を確認
    before_record = MemberSystem.find(params[:id])

    #対象レコードの更新
    @record.updated_status = 2
    @record.update(member_system_params)

    ##開始日に変更がある場合は前のレコードの終了日を合わせて更新
    unless before_record.started_on == Date.parse(params[:member_system][:started_on])
      #対象レコードを取得
      day = before_record.started_on - 1
      update_record = MemberSystem.get_mylist_day(params[:member_system][:user_id],day)
      #終了日を更新
      update_day = Date.parse(params[:member_system][:started_on]) - 1
      update_record.ended_on = update_day
      update_record.updated_status = 4
      update_record.updated_user = session[:user_id]
      update_record.save
    end

    ##ページ再表示
    flash[:notice] = t('message.update')
    set_member_list(params[:member_system][:user_id],"MemberSystem")

  end

  def destroy
    ##削除処理

    #1つ前の履歴の終了日を無期限に変更
    day = Date.parse(@record.started_on.to_s) - 1
    update_record = MemberSystem.get_mylist_day(@record.user_id,day)
    update_record.ended_on = '2099-12-31'
    update_record.updated_status = 4
    update_record.updated_user = session[:user_id]
    update_record.save

    #対象レコードを削除
    @record.updated_status = 3
    @record.updated_user = session[:user_id]
    @record.deleted_at = Time.now
    @record.save

    ##ページ再表示
    flash[:notice]  = t('message.delete')
    set_member_list(@record.user_id,"MemberSystem")

  end

  private
    def set_member_system
      @record = MemberSystem.find(params[:id])
    end

    def member_system_params
      params.require(:member_system).permit(:user_id, :started_on, :ended_on, :enable, :member_role_id, :memo, :deleted_at)
    end
end

app/views/member_systems/_list.html.slim
== render 'shared/member_navi'

.row
  .col-xs-12.col-md-6
    = link_to '#' , id: "open_all" do
      i.fa.fa-plus-square-o
      '
      u
        = t('veiw_control.open_all')
      '
    = link_to '#' , id: "close_all" do
      i.fa.fa-minus-square-o
      '
      u
        = t('veiw_control.close_all')

  .col-xs-12.col-md-3
    p.text-right
      = link_to csv_member_systems_path(format: :csv , user_id: @user_id) do
        i.fa.fa-download
        '
        u
          = t('veiw_control.file_export')
      '
  .col-xs-12.col-md-3
    p.text-right
      = link_to new_member_system_path(user_id: @user_id), :remote => true do
        i.fa.fa-plus-square
        '
        u
          = t('link.new_history')

.row
#alert
#new

.row
  .col-xs-12.col-md-12
    table.table.table-hover
      thead
        tr
          - @view_columns.each  do |view_column|
            th = view_column.column_name
    table.table.table-bordered.table-hover
      tbody
        - @records.each.with_index(1)  do |result, i|

          /現在有効なレコードを判定
          - if result.started_on > Date.current
            /未来
            - color = "warning"
          - elsif result.started_on <= Date.current and result.ended_on >= Date.current
            /現在
            - color = "info"
          - else
            /過去
            - color = "default"

          tr class = "#{color}"
            - @view_columns.each  do |view_column|
              td = result["#{view_column.column_name}"]
            td
              p.text-right
                = link_to member_system_path(result.id) , :remote => true do
                  i.fa.fa-pencil-square-o
                  '
                  u
                    = t('link.show')
              p.text-right
                = link_to edit_member_system_path(result.id) , :remote => true do
                  i.fa.fa-pencil-square-o
                  '
                  u
                    = t('link.edit')
                '
                /最新履歴のみ削除ボタンを表示
                - if i == 1
                  = link_to member_system_path(result.id), method: :delete, data: {confirm: t('message.delete_alert')}, :remote => true  do
                    i.fa.fa-trash-o
                    '
                    u
                      = t('link.delete')

          tr id = "#{result.id}_show"
            td colspan="6"
              div class = "form-group"
                div class = "col-md-4 control-label"
                  b  aaaaaaaaa
                div class = "col-md-8"
                  = result.started_on

          div id = "#{result.id}_edit"

app/views/member_systems/_new.html.slim
.panel.panel-success
  .panel-heading
    h3.panel-title
      = t('link.new_history')
  .panel-body
    = form_for(@record, remote: true) do |f|
      .row
        .form-horizontal.col-xs-12.col-md-8
          == render :partial => 'shared/form_column', :locals => {:f => f, form_columns: @form_columns}
          == render :partial => 'shared/form_footer', :locals => {:f => f, form_footers: @form_footers}

app/views/member_systems/_result.html.slim
== render :partial => 'shared/paginate' , locals: {results: @results}
== render :partial => 'shared/view_result', :locals => {results: @results, view_columns: @view_columns}

app/views/member_systems/_show.html.slim
hr
  = form_for(@record, remote: true) do |f|
    /== render :partial => 'shared/form', :locals => {:f => f, forms: @forms}

    .row
      .form-horizontal.col-xs-12.col-md-8
        == render :partial => 'shared/form_column', :locals => {:f => f, form_columns: @form_columns}
        == render :partial => 'shared/form_footer', :locals => {:f => f, form_footers: @form_footers}

        .col-md-8.col-md-offset-4
          = link_to cancel_edit_member_names_path(id: @record.id), class: "btn btn-danger", :remote => true do
            i.fa.fa-close
            '
            = t('link.cancel')

app/views/member_systems/cancel.js.erb
$("#new").html("")

app/views/member_systems/cancel_edit.js.erb
$("#<%= @id %>_edit").empty();
$("#<%= @id %>").show();

app/views/member_systems/create.js.erb
$("#list").html("<%= escape_javascript(render :partial => "list") %>");
$("#alert").html("<div class='alert alert-success'><a class='close' data-dismiss='alert'>×</a><%= escape_javascript(flash[:notice])%></div>");

app/views/member_systems/destroy.js.erb
$("#list").html("<%= escape_javascript(render :partial => "list") %>");
$("#alert").html("<div class='alert alert-success'><a class='close' data-dismiss='alert'>×</a><%= escape_javascript(flash[:notice])%></div>");

app/views/member_systems/edit.js.erb
$("#<%= @id %>").hide();
$("#<%= @id %>_edit").html("<%= escape_javascript(render 'edit') %>")

$(function($){
  $(".edit_member_name").validationEngine();
  $('.input-group.date').datepicker({
    language: 'ja',
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked"
  });
});

app/views/member_systems/index.html.slim
== render 'shared/member_menu'
br
br
.row
  .col-xs-12.col-md-8

    = search_form_for @q, :remote => true do |f|
      .col-md-9.form-inline
        = f.hidden_field :started_on_lteq , value: Date.current
        = f.hidden_field :ended_on_gteq, value: Date.current
        = f.search_field :member_role_name_cont, class: "form-control col-md-6", placeholder: "ロール名"
        '
        = button_tag :type => "submit", name: 's', class: "btn btn-primary" , id: "search_btn" do
          i.fa.fa-search
          '
          = t('link.search')

  .col-xs-12.col-md-4
    .text-right
      u
        = link_to member_roles_path
          i.fa.fa-cog
          '
          = t('link.index_member_role')

  /検索結果部分
.row
  #result
    == render "result"

app/views/member_systems/index.js.erb
$("#result").html("<%= escape_javascript(render :partial => 'result') %>");

app/views/member_systems/new.js.erb
$("#new").html("")
$("#new").html("<%= escape_javascript(render 'new') %>")

$(function($){
  $("#new_member_name").validationEngine();
  $('.input-group.date').datepicker({
    language: 'ja',
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked"
  });
});

app/views/member_systems/show.js.erb
$("#<%= @id %>_show").show();

app/views/member_systems/update.js.erb
$("#list").html("<%= escape_javascript(render :partial => "list") %>");
$("#alert").html("<div class='alert alert-success'><a class='close' data-dismiss='alert'>×</a><%= escape_javascript(flash[:notice])%></div>");