config/routes.rb
Rails.application.routes.draw do

  resources :config_columns
  resources :config_view_columns
  scope "(:locale)" do

    resources :ability_requirements
    resources :ability_groupings
    resources :config_form_columns
    resources :config_form_footers
    resources :config_views
    resources :evaluation_details
    resources :evaluation_headers do
      member do
        get :entry
        get :edit_evaluator
      end
    end
    resources :evaluation_settings
    resources :evaluation_objectives do
      member do
        get :delete
      end
    end

    resources :evaluation_events do
      member do
        get :delete
      end
    end
    resources :members do
      member do
        get :profile_tabs
        get :profile_details
        get :profile
      end
    end
    resources :member_communications do
      collection do
        get :cancel_edit
      end
    end
    resources :member_names do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_systems do
      collection do
        get :cancel
        get :cancel_edit
        get :csv
      end
    end
    resources :member_tables
    resources :member_role_details do
      member do
        get :block_edit
      end
    end
    resources :member_roles
    resources :table_settings
    resources :user_images
    resources :user_passwords
    resources :users do
      collection do
        get :activate
        get :account_new
        post :account_create
        get :account_finish
        get :password_reset_check
        get :password_reset_error
        get :password_reset_finish
      end
      member do
        get :password_reset
        patch :password_reset_update
        get :delete
      end
    end

    get  'login' => 'login#index'
    post 'login/auth' => 'login#auth'

    get  'logout' => 'login#logout'

    get  'registers' => 'registers#index'
    post 'registers/auth' => 'registers#auth'
    post 'registers/email_check' => 'registers#email_check'
    get  'registers/password_reset' => 'registers#password_reset'

    get  'configurations' => 'configurations#index'

    get  'homes/user' => 'homes#user'
    get  'evaluations/index' => 'evaluations#index'
    get  'members/profile/:id' => 'members#profile'

  end

end

app/models/member_role_detail.rb
class MemberRoleDetail < ActiveRecord::Base
  belongs_to :member_role

  default_scope { where("member_role_details.deleted_at IS NULL") }

end

app/controllers/member_role_details_controller.rb
class MemberRoleDetailsController < ApplicationController
  before_action :set_member_role_detail, only: [:show, :edit, :destroy]

  def index
    @member_role_details = MemberRoleDetail.all
  end

  def show
  end

  def new
    @member_role_detail = MemberRoleDetail.new
  end

  def edit
    @member_tables = MemberTable.all
  end

  def block_edit
    @member_tables = MemberTable.all
  end

  def create
    @member_role_detail = MemberRoleDetail.new(member_role_detail_params)

    respond_to do |format|
      if @member_role_detail.save
        format.html { redirect_to @member_role_detail, notice: 'Member role detail was successfully created.' }
        format.json { render :show, status: :created, location: @member_role_detail }
      else
        format.html { render :new }
        format.json { render json: @member_role_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    #Delete
    MemberRoleDetail.where(member_role_id: params[:id]).update_all(deleted_at: Time.now )

    #Insert
    records = MemberTable.all
    records.each do |record|
      if params[:use_type][record.id.to_s] == "1"
        member_role_detail = MemberRoleDetail.new
        member_role_detail.member_role_id = params[:id]
        member_role_detail.member_table_id = record.id
        member_role_detail.use_type = params[:use_type][record.id.to_s]
        member_role_detail.scope_type = params[:scope_type][record.id.to_s]
        member_role_detail.level_type = params[:level_type][record.id.to_s]
        member_role_detail.time_type = params[:time_type][record.id.to_s]
        member_role_detail.crud_type = params[:crud_type][record.id.to_s]
        member_role_detail.save
      end
    end

    redirect_to member_role_path(params[:id])

  end

  def destroy
    @member_role_detail.destroy
    respond_to do |format|
      format.html { redirect_to member_role_details_url, notice: 'Member role detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_member_role_detail
      @member_role_detail = MemberRoleDetail.find(params[:id])
    end

    def member_role_detail_params
      params.require(:member_role_detail).permit(:member_table_id, :use_type, :scope_type, :level_type, :time_type, :crud_type)
    end
end

app/views/member_role_details/_form.html.slim
= form_for @member_role_details do |f|

  table
    thead
      tr
        th Code
        th Name
        th Category
        th Hierarchy level
        th Font awesome
        th Font awesome

    tbody
      - @member_tables.each do |member_table|
        tr
          td = member_table.category
          td = member_table.code
          td
            i class = "fa #{member_table.font_awesome}"
          td = member_table.name
          td = select :use_type, id = "#{member_table.code}", [["未使用", 0], ["利用する", 1]]
          td = select :scope_type, id = "#{member_table.code}", [["同じ所属", 1], ["同じグループ", 2], ["全員", 3]]
          td = select :level_type, id = "#{member_table.code}", [["配下", 1], ["同列まで", 2], ["全員", 3]]
          td = select :time_type, id = "#{member_table.code}", [["全て", 1], ["過去～現在", 2], ["現在～未来", 3], ["現在のみ", 4]]
          td = select :crud_type, id = "#{member_table.code}", [["参照のみ", 1], ["編集可能", 2]]

  .actions = f.submit

app/views/member_role_details/block_edit.html.slim
.col-md-12
  .panel.panel-default
    .panel-heading.text-right

    .panel-body
      = form_tag({action: 'update'}, {:method => 'patch'})

        table.table
          thead
            tr
              th = MemberTable.human_attribute_name('category')
              th = MemberTable.human_attribute_name('code')
              th = MemberTable.human_attribute_name('name')
              th = MemberRoleDetail.human_attribute_name('use_type')
              th = MemberRoleDetail.human_attribute_name('scope_type')
              th = MemberRoleDetail.human_attribute_name('level_type')
              th = MemberRoleDetail.human_attribute_name('time_type')
              th = MemberRoleDetail.human_attribute_name('crud_type')
          tbody
            - @member_tables.each do |member_table|
              /カテゴリ
              - case member_table.hierarchy_level
              /カテゴリ
              - when 1 then
                tr.success
                  td = member_table.category
                  td
                  td
                    i class = "fa #{member_table.font_awesome}"
                    '
                    = member_table.name
                  td
                  td
                  td
                  td
                  td
              /各機能
              - when 2 then
                tr
                  td
                  td = member_table.id
                  td
                    i class = "fa #{member_table.font_awesome}"
                    '
                    = member_table.name
                  - if get_member_role_detail(1,member_table.id).blank?
                    td = select :use_type, id = "#{member_table.id}", [["未使用", 0], ["利用する", 1]]
                    td = select :scope_type, id = "#{member_table.id}", [[get_member_role_detail_scope_type(1), 1], [get_member_role_detail_scope_type(2), 2], [get_member_role_detail_scope_type(3), 3]]
                    td = select :level_type, id = "#{member_table.id}", [[get_member_role_detail_level_type(1), 1], [get_member_role_detail_level_type(2), 2], [get_member_role_detail_level_type(3), 3]]
                    td = select :time_type, id = "#{member_table.id}", [[get_member_role_detail_time_type(1), 1], [get_member_role_detail_time_type(2), 2], [get_member_role_detail_time_type(3), 3], [get_member_role_detail_time_type(4), 4]]
                    td = select :crud_type, id = "#{member_table.id}", [[get_member_role_detail_crud_type(1), 1], [get_member_role_detail_crud_type(2), 2]]
                  - else
                    td.warning = select :use_type, id = "#{member_table.id}", [["未使用", 0], ["利用する", 1]], :selected => 1
                    td = select :scope_type, id = "#{member_table.id}", [[get_member_role_detail_scope_type(1) , 1], [get_member_role_detail_scope_type(2), 2], [get_member_role_detail_scope_type(3), 3]], :selected => @member_role_details.scope_type
                    td = select :level_type, id = "#{member_table.id}", [[get_member_role_detail_level_type(1), 1], [get_member_role_detail_level_type(2), 2], [get_member_role_detail_level_type(3), 3]], :selected => @member_role_details.level_type
                    td = select :time_type, id = "#{member_table.id}", [[get_member_role_detail_time_type(1), 1], [get_member_role_detail_time_type(2), 2], [get_member_role_detail_time_type(3), 3], [get_member_role_detail_time_type(4), 4]], :selected => @member_role_details.time_type
                    td = select :crud_type, id = "#{member_table.id}", [[get_member_role_detail_crud_type(1), 1], [get_member_role_detail_crud_type(2), 2]], :selected => @member_role_details.crud_type

        = button_tag :type => "submit", class: "btn btn-success" do
          i.fa.fa-floppy-o
          '
          = t('link.save')

app/views/member_role_details/edit.html.slim
h1 Editing member_role_detail

== render 'form'

= link_to 'Show', @member_role_detail
'|
= link_to 'Back', member_role_details_path

app/views/member_role_details/index.html.slim
h1 Listing member_role_details

table
  thead
    tr
      th Member table
      th Use type
      th Scope type
      th Level type
      th Time type
      th Crud type
      th
      th
      th

  tbody
    - @member_role_details.each do |member_role_detail|
      tr
        td = member_role_detail.member_table_id
        td = member_role_detail.use_type
        td = member_role_detail.scope_type
        td = member_role_detail.level_type
        td = member_role_detail.time_type
        td = member_role_detail.crud_type
        td = link_to 'Show', member_role_detail
        td = link_to 'Edit', edit_member_role_detail_path(member_role_detail)
        td = link_to 'Destroy', member_role_detail, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Member role detail', new_member_role_detail_path

app/views/member_role_details/new.html.slim
h1 New member_role_detail

== render 'form'

= link_to 'Back', member_role_details_path

app/views/member_role_details/show.html.slim
p#notice = notice

p
  strong Member table:
  = @member_role_detail.member_table_id
p
  strong Use type:
  = @member_role_detail.use_type
p
  strong Scope type:
  = @member_role_detail.scope_type
p
  strong Level type:
  = @member_role_detail.level_type
p
  strong Time type:
  = @member_role_detail.time_type
p
  strong Crud type:
  = @member_role_detail.crud_type

= link_to 'Edit', edit_member_role_detail_path(@member_role_detail)
'|
= link_to 'Back', member_role_details_path